clear all;
syms a d alpha theta;

Tx = [1 0 0 a;...
    0 cos(alpha) -sin(alpha) 0;...
    0 sin(alpha) cos(alpha) 0;...
    0 0 0 1];

Tz = [cos(theta) -sin(theta) 0 0;...
      sin(theta) cos(theta) 0 0;...
      0 0 1 d;...
      0 0 0 1];
 
T = Tx*Tz
%subs(T,[theta,alpha],[0,-pi/2])


